=== ocsf/ocsf-schema/metaschema/common-event-object.schema.json
{
    "$id": "https://schema.ocsf.io/common-event-object.schema.json",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "Object",
    "description": "Common metaschema shared between objects and event classes.",
    "type": "object",
    "anyOf": [
        {
            "required": [
                "description",
                "caption",
                "name",
                "attributes"
            ]
        },
        {
            "required": [
                "extends"
            ]
        }
    ],
    "properties": {
        "@deprecated": {
            "$ref": "deprecated.schema.json"
        },
        "description": {
          "type": "string",
          "description": "A concise description of the object."
        },
        "caption": {
          "type": "string",
          "description": "A short, human friendly name for the object."
        },
        "name": {
          "type": "string",
          "description": "A name of the object. It must be a unique name. The name is all lower case letters, combine words using underscore.",
          "pattern": "^[a-z0-9_]*$"
        },
        "extends": {
            "type": "string",
            "description": "An object that this one extends from."
        },
        "constraints": {
            "type": "object",
            "description": "Constraints that apply to the attribute requirements.",
            "properties": {
                "at_least_one": {
                    "type": "array",
                    "items": {"type": "string"}
                },
                "just_one": {
                    "type": "array",
                    "items": {"type": "string"}
                }
            },
            "additionalProperties": false
        },
        "profiles": {
            "type": "array",
            "items": {"type": "string"},
            "description": "The list of profiles used to create the event."
        },
        "attributes": {
            "type": "object",
            "description": "A dictionary of attributes for the object.",
            "properties": {
                "$include": {
                    "description": "A reference to another schema for attributes to include.",
                    "type": "array",
                    "items": {
                        "type": "string",
                        "format": "uri-reference"
                    }
                }
            },
            "patternProperties": {
                "^[a-z0-9_]*$": {
                    "$ref": "attribute.schema.json"
                }
            },
            "additionalProperties": false
        }
    }
}

=== ocsf/ocsf-schema/objects/reported_by.json
{
  "caption": "Reported By",
  "description": "The entity from which an event or finding was first reported.",
  "extends": "object",
  "name": "reported_by",
  "attributes": {
    "hostname": {
      "description": "The hostname of the entity from which the event or finding was first reported.",
      "requirement": "recommended"
    },
    "ip": {
      "description": "The IP address of the entity from which the event or finding was first reported.",
      "requirement": "recommended"
    }
  },
  "constraints": {
    "at_least_one": [
      "hostname",
      "ip"
    ]
  }
}
