=== ocsf/ocsf-schema/metaschema/dictionary.schema.json
{
    "$id": "https://schema.ocsf.io/dictionary.schema.json",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "Dictionary",
    "description": "An attribute dictionary of all available attributes and their types. Event classes are particular sets of attributes from the dictionary.",
    "type": "object",
    "required": [
        "caption",
        "name"
    ],
    "properties": {
        "description": {
            "type": "string",
            "description": "A concise description of the dictionary."
        },
        "caption": {
            "type": "string",
            "description": "A short, human friendly name for the dictionary."
        },
        "name": {
            "type": "string",
            "description": "A name of the dictionary. It must be a unique name. The name is all lower case letters, combine words using underscore.",
            "pattern": "^[a-z0-9_]*$"
        },
        "attributes": {
            "type": "object",
            "description": "A set of attributes defined by the dictionary.",
            "patternProperties": {
                "^[a-z0-9_]*$": {
                    "$ref": "dictionary-attribute.schema.json"
                }
            },
            "additionalProperties": false
        },
        "types": {
            "type": "object",
            "description": "A set of data types defined by the dictionary.",
            "required": [
                "caption"
            ],
            "properties": {
                "caption": {
                    "type": "string",
                    "description": "A short, human friendly name for these data types."
                },
                "description": {
                    "type": "string",
                    "description": "A concise description of these data types."
                },
                "attributes": {
                    "type": "object",
                    "description": "A set of type attributes defined by the dictionary.  Type attributes must be all lowercase and end in '_t' by convention.",
                    "patternProperties": {
                        "^[a-z0-9_]*$": {
                            "allOf": [
                                {
                                    "$ref": "attribute.schema.json"
                                }, 
                                {
                                    "properties": {
                                        "max_len": {
                                            "type": "integer",
                                            "description": "The maximum length of this data type.",
                                            "minimum": 0
                                        },
                                        "observable": {
                                            "$ref": "observable.schema.json"
                                        },
                                        "range": {
                                            "type": "array",
                                            "description": "A range of values that are valid for this data type.",
                                            "minItems": 2,
                                            "maxItems": 2
                                        },
                                        "regex": {
                                            "type": "string",
                                            "description": "A regular expression constraint for this data type.",
                                            "format": "regex"
                                        },
                                        "type": {
                                            "type": "string",
                                            "description": "The data type for this attribute. Should reference another defined type."
                                        },
                                        "type_name": {
                                            "type": "string",
                                            "description": "The human-readable name of the data type for this attribute."
                                        },
                                        "values": {
                                            "type": "array",
                                            "description": "A set of fixed values for this data type."
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "additionalProperties": false
                }
            }
        }
    }
}

=== ocsf/ocsf-schema/extensions/query/dictionary.json
{
  "caption": "Attribute Dictionary",
  "description": "The Attribute Dictionary defines schema attributes and includes references to the events and objects in which they are used.",
  "name": "dictionary",
  "attributes": {
    "raw_data": {
      "caption": "Raw Data",
      "description": "The event data as received from the event source.",
      "type": "json_t"
    },
    "recipient_users": {
      "caption": "Recipient Users",
      "description": "The users receiving the email",
      "is_array": true,
      "type": "user"
    },
    "record_id": {
      "description": "Unique identifier for record or event",
      "caption": "Record ID",
      "type": "string_t"
    },
    "sender_users": {
      "caption": "Sender Users",
      "description": "The user who sent the email",
      "type": "user"
    },
		"reputations": {
			"caption": "Reputations",
			"description": "Reputation score as reported by provider",
			"is_array": true,
			"type": "reputation" 
		},
		"findings": {
			"caption": "Findings",
			"description": "The findings from threat intelligence platforms",
			"type": "finding",
			"is_array": true
		},
		"filenames": {
      "caption": "Filenames",
			"description": "The names a file is known by.",
			"type": "string_t",
			"is_array": true
		},
		"asn": {
			"description": "The 2- or 4-byte Autonomous System Number (ASN)",
			"type": "integer_t",
			"caption": "ASN"
		},
		"asn_owner": {
			"description": "The Autonomous System (AS) owner",
			"type": "string_t",
			"caption": "AS Owner"
		},
    "dns_entries": {
      "caption": "DNS Entries",
      "description": "The Domain Name System (DNS) entries from passive DNS logs or a direct query for enrichment.",
      "is_array": true,
      "type": "dns_answer"
    },
		"full_name": {
      "caption": "Full Name",
      "description": "The full name of the person, as per the LDAP Common Name attribute (cn).",
      "type": "string_t"
    },
    "ip_intelligence": {
      "caption": "IP Intelligence",
      "description": "Insights from threat intelligence platforms about IP Address",
      "type": "ip_intelligence"
    },
    "last_login_time": {
      "caption": "Last Login",
      "description": "The last time when the user logged in.",
      "type": "timestamp_t"
    },
    "is_array": {
    	"type": "boolean_t",
    	"caption": "Is Array",
    	"description": "If true, the value is understood to be an array. Otherwise it is assumed to be a scalar."
    },
    "unmapped": {
      "caption": "Unmapped",
      "description": "Data from the source that was not mapped into the schema.",
    	"type": "unmapped",
    	"is_array": true
    },
    "xattributes": {
      "caption": "Extended Attributes",
      "description": "An unordered collection of zero or more name/value pairs where each pair represents a file or folder extended attribute.</p>For example: Windows alternate data stream attributes (ADS stream name, ADS size, etc.), user-defined or application-defined attributes, ACL, owner, primary group, etc. Examples from DCS: </p><ul><li><strong>ads_name</strong></li><li><strong>ads_size</strong></li><li><strong>dacl</strong></li><li><strong>owner</strong></li><li><strong>primary_group</strong></li><li><strong>link_name</strong> - name of the link associated to the file.</li><li><strong>hard_link_count</strong> - the number of links that are associated to the file.</li></ul>",
      "type": "json_t"
    }
  }
}

=== ocsf/ocsf-schema/templates/object_name.json
{
  "caption": "REPLACE me with a short, human friendly name for the object.",
  "description": "REPLACE me with a concise description of the object.",
  "name": "REPLACE me with a name of the object. It must be unique name. The name is all lower case letters, combine words using underscore.",
  "attributes": {
    "DELETE ME": "Ensure you adjust 'requirement' for all the attributes as desired.",
    "attribute_1": {
      "description": "REPLACE me with an overridden description of an attribute, IF NEEDED.",
      "requirement": "required"
    },
    "attribute_2": {
      "requirement": "optional"
    },
    "attribute_n": {
      "requirement": "recommended"
    }
  }
}

=== ocsf/ocsf-schema/extensions/dev/categories.json
{
  "caption": "New Categories",
  "name": "category",
  "description": "The new event categories.",
  "attributes": {
    "policy": {
      "caption": "Policy",
      "description": "Policy events report policy violations.",
      "uid": 31
    },
   "discovery": {
      "caption": "Discovery",
      "description": "Discovery events report the existence of devices, files, processes, registry keys, and other objects.",
      "uid": 32
    },
    "remediation": {
      "caption": "Remediation",
      "description": "Remediation events report the results the remediation status of files, processes, registry keys, and other objects.",
      "uid": 33
    },
    "application": {
      "caption": "Application",
      "description": "Application Lifecycle events report detailed information about the behavior of applications and services.",
      "uid": 34
    },
    "diagnostic": {
      "caption": "Diagnostic",
      "description": "Diagnostic events report status, errors, and performance statistics of a service or application.",
      "uid": 35
    },
    "virtualization": {
      "caption": "Virtualization Activity",
      "description": "Hypervisor-based (virtual machine) and container-based virtualization activity events.",
      "uid": 36
    },
    "storage": {
      "caption": "Storage Activity",
      "description": "Storage Activity events.",
      "uid": 37
    },
    "cloud": {
      "caption": "Cloud Activity",
      "description": "Cloud Activity events.",
      "uid": 38
    }
  }
}

=== ocsf/ocsf-schema/extensions/linux/dictionary.json
{
  "caption": "Attribute Dictionary",
  "description": "The Attribute Dictionary defines schema attributes and includes references to the events and objects in which they are used.",
  "name": "dictionary",
  "attributes": {
    "auid": {
      "caption": "Audit User ID",
      "description": "The audit user assigned at login by the audit subsystem.",
      "type": "integer_t"
    },
    "euid": {
      "caption": "Effective User ID",
      "description": "The effective user under which this process is running.",
      "type": "integer_t"
    },
    "egid": {
      "caption": "Effective Group ID",
      "description": "The effective group under which this process is running.",
      "type": "integer_t"
    }
  }
}

=== ocsf/ocsf-schema/objects/job_action.json
{
  "caption": "Job Action",
  "description": "The action that will be performed by the job when certain conditions are met.",
  "name": "job_action",
  "attributes": {
    "type_id": {
      "description": "The job action type.",
      "requirement": "required",
      "enum": {
        "0": {
          "caption": "Unknown",
	  "description": "The performed action is unknown."
	},
	"1": {
	  "caption": "COM Handler",
	  "description": "The action fires a COM handler."
	},
	"2": {
	  "caption": "Execute",
	  "description": "The action executes a command-line operation."
	},
	"3": {
	  "caption": "E-mail",
	  "description": "The action sends an email."
	},
	"4": {
	  "caption": "Show Message",
	  "description": "The action shows a message box with specified message and title."
	},
	"99": {
	  "caption": "Other",
	  "description": "The performed action is not mapped. See the <code>type</code> attribute, which contains a data source specific value."
	}
      }
    },
    "type": {
      "description": "The job action type, normalized to the caption of the <code>type_id</code> value. In the case of 'Other', it is defined by the event source.",
      "requirement": "recommended"
    },
    "cmd_line": {
      "description": "When <code>type_id</code> is <code>Execution (3)</code>, this describes the command line that is executed.<br/><br/>When <code>type_id</code> is <code>COM Handler (1)</code>, this <em>may</em> describe the DLL path stored in the COM component's <code>InprocServer32</code> key or the command line stored in the COM component's <code>LocalServer32</code> key.",
      "requirement": "optiona"
    },
    "properties": {
      "description": "The list of properties associated with the performed action.<br>Can be populated with additional attributes of a program execution process, COM object attributes, fields of a message box or an email.",
      "requirement": "recommended"
    }
  }
}

=== ocsf/ocsf-schema/objects/job_trigger.json
{
  "caption": "Job Trigger",
  "description": "The condition or event that, when met, will initiate the job to perform specified actions.",
  "name": "job_trigger",
  "attributes": {
    "event_codes": {
      "description": "Event identifiers that pertain to the job trigger. Should be populated when the <code>Event (3)</code> type is specified.",
      "requirement": "optional"
    },
    "log_sources": {
      "description": "A collection of log systems or components that pertain to the job trigger. Should be populated when the <code>Event (3)</code> type is specified.",
      "requirement": "optional"
    }, 
   "properties": {
      "description": "The list of properties associated with the trigger.<br>Can be used to describe time boundaries of the job, amount of repetitions or when the job should be activated or expired.",
      "requirement": "recommended"
    },
    "type": {
      "description": "The job trigger type, normalized to the caption of the <code>type_id</code> value. In the case of 'Other', it is defined by the event source.",
      "requirement": "recommended"
    },
    "type_id": {
      "description": "The job trigger type, i.e. the condition that must be met for the job to perform its action.",
      "requirement": "required",
      "enum": {
        "0": {
          "caption": "Unknown",
	  "description": "The trigger is unknown."
	},
	"1": {
	  "caption": "Boot",
	  "description": "The job is triggered on a system boot."
	},
	"2": {
	  "caption": "Schedule",
	  "description": "The job is triggered on a specific schedule. Properties should be populated with respective time bounds."
	},
	"3": {
	  "caption": "Event",
	  "description": "The job is triggered when the specific event occurs. Properties should be populated with respective event sources and identifiers."
	},
	"99": {
	  "caption": "Other",
	  "description": "The job trigger is unmapped. See the <code>type</code> attribute, which contains a data source specific value."
	}
      }
    },
    "user": {
      "description": "The user that pertains to the job trigger. Can be populated when the <code>Event (3)</code> type that bounds to specific user is used.",
      "requirement": "optional"
    }
  }
}
